Login
szut-fa19d/nhs-d pull request #25
Opened 2020-12-11 10:00 UTC by jgerdes5

2020-12-11 10:27 UTC, FunctionDJ requested changes
Ein paar Sachen können jetzt schon gefixt werden, ein paar Andere erst nach dem Merge von #23 (steht bei den Kommentaren dabei)

2020-12-11 10:27 UTC, FunctionDJ commented on src/main/java/controller/AddUserController.java
> +        if (!username.trim().isEmpty() && !password.trim().isEmpty() && !passwordConfirm.trim().isEmpty() && comboGroup.getValue() != null) {
Besser:
```java
if (username.trim().isEmpty() || password.trim.isEmpty() ...) {
  return;
}

// do stuff
```

2020-12-11 10:27 UTC, FunctionDJ commented on src/main/java/controller/AllUserController.java
> +public class AllUserController {
wenn #23 gemerged ist, dann schauen, ob
```java
extends CommonListController<T>
```
sinnig ist

2020-12-11 10:27 UTC, FunctionDJ commented on src/main/java/controller/LoginController.java
> +        if(hashedPassword != null && hashedPassword.equals(user.getPassword())) {
```java
if (hashedPassword == null || !hashedPassword.equals(user.getPassword())) {
  error.setVisible(true);
  return;
}

// success code
```

2020-12-11 10:27 UTC, FunctionDJ commented on src/main/java/datastorage/UserDAO.java
> +        );    }
samma, ey

2020-12-11 10:27 UTC, FunctionDJ commented on src/main/java/datastorage/UserDAO.java
> +        );    }
was' das denn

2020-12-11 10:27 UTC, FunctionDJ commented on src/main/java/model/Group.java
> +public class Group {
nach merge von #23 bitte `extends DatabaseEntry`

2020-12-17 13:16 UTC, JLNPWRLFT submitted a review, later dismissed

2020-12-17 13:27 UTC, bebetepp approved these changes

2020-12-17 14:25 UTC, Hannes-Neunaber submitted a review, later dismissed

2020-12-17 18:23 UTC, FunctionDJ approved these changes

2020-12-17 18:26 UTC, merged